### ISSUE TITLE
Cross Compile nodejs https://github.com/nodejs/node

### ISSUE THREAD

**Issue by Mounika1494** [netbeast/docs#23]
After all configurations after command make i am getting an error

/node/out/Release/icupkg Syntax error - bad function name

Help me out in resolving this error

**Comment by luisfpinto** [comment]
Could you please provide more information about what commands you did?

Thanks!

**Comment by Mounika1494** [comment]
Hi,
These are the commands.See the attachment

**Comment by luisfpinto** [comment]
I need more information. Where are you trying to cross-compile node.js. 

Thanks

**Comment by Mounika1494** [comment]
I am trying to cross compile node.js for  a router (UAP-AC-PRO) which is
mips architecture running on  OpenWRT.

**Comment by jsdario** [comment]
@Mounika1494 be aware that attachments are not seen on the github interface. Many people disable email notifications on open source, due to the huge amount of them they can eventually receive. We yet not have seen any of the commands you did.

**Comment by Mounika1494** [comment]
[https://github.com/netbeast/docs/wiki/Cross-Compile-Nodejs-for-OpenWrt](url) followed the steps provided here for openwrt toolchain

**Comment by jsdario** [comment]
We are no experts on this topic, however if you [research a little bit](http://unix.stackexchange.com/questions/245331/shell-valid-function-name-characters)...
```
/node/out/Release/icupkg Syntax error - bad function name
```
Turns out to be a POSIX error, like `/node/out/Release/icupkg` is badly formatted or uses an interpreter which is not available.

I am afraid we can't really help any further than that. I expect you have properly inputed your architecture where it says `your-architecture` in the commands.

Else I'll leave this issue open in case anyone in the community can help.
